In [74]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBRegressor, XGBClassifier
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder

In [75]:
dataset = pd.read_csv('Price.csv')
x = dataset.iloc[:, :6].values
y = dataset.iloc[:,  6].values

In [76]:
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])
x[:, 3] = le.fit_transform(x[:, 3])
x[:, 4] = le.fit_transform(x[:, 4])
print(x)

[[63 1 1 1 1 'Shahran']
 [60 1 1 1 1 'Shahran']
 [79 2 1 1 1 'Pardis']
 [95 2 1 1 1 'Shahrake Qods']
 [123 2 1 1 1 'Shahrake Gharb']
 [70 2 1 1 0 'North Program Organization']
 [87 2 1 1 1 'Pardis']
 [59 1 1 1 1 'Shahran']
 [54 2 1 1 0 'Andisheh']
 [71 1 1 1 1 'West Ferdows Boulevard']
 [68 2 1 1 1 'West Ferdows Boulevard']
 [64 1 1 1 1 'Narmak']
 [54 1 0 1 1 'Narmak']
 [136 3 1 1 1 'Saadat Abad']
 [95 2 1 1 1 'Zafar']
 [63 1 0 1 0 'Islamshahr']
 [155 3 1 1 1 'Narmak']
 [64 2 0 1 0 'Pirouzi']
 [140 3 1 1 1 'West Ferdows Boulevard']
 [42 1 0 1 0 'Pirouzi']
 [93 2 1 1 1 'Shahrake Gharb']
 [87 2 1 1 1 'Shahrake Shahid Bagheri']
 [65 1 1 1 1 'Shahran']
 [99 2 1 1 1 'Moniriyeh']
 [105 2 1 1 1 'Saadat Abad']
 [160 3 1 1 1 'Velenjak']
 [77 2 1 1 1 'Amirieh']
 [123 2 1 1 1 'Pirouzi']
 [110 2 1 1 1 'Southern Janatabad']
 [100 2 1 1 1 'West Ferdows Boulevard']
 [90 2 0 1 0 'Salsabil']
 [49 1 1 1 1 'West Ferdows Boulevard']
 [96 2 1 1 1 'Zargandeh']
 [67 2 1 1 0 'Feiz Garden']
 [68 2 1 1 1 'West 

In [77]:
ct = ColumnTransformer(transformers=[('encoder', OrdinalEncoder(), [5])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[55.0 63 1 1 1 1]
 [55.0 60 1 1 1 1]
 [37.0 79 2 1 1 1]
 [53.0 95 2 1 1 1]
 [52.0 123 2 1 1 1]
 [30.0 70 2 1 1 0]
 [37.0 87 2 1 1 1]
 [55.0 59 1 1 1 1]
 [3.0 54 2 1 1 0]
 [62.0 71 1 1 1 1]
 [62.0 68 2 1 1 1]
 [29.0 64 1 1 1 1]
 [29.0 54 1 0 1 1]
 [46.0 136 3 1 1 1]
 [64.0 95 2 1 1 1]
 [22.0 63 1 0 1 0]
 [29.0 155 3 1 1 1]
 [39.0 64 2 0 1 0]
 [62.0 140 3 1 1 1]
 [39.0 42 1 0 1 0]
 [52.0 93 2 1 1 1]
 [54.0 87 2 1 1 1]
 [55.0 65 1 1 1 1]
 [28.0 99 2 1 1 1]
 [46.0 105 2 1 1 1]
 [60.0 160 3 1 1 1]
 [2.0 77 2 1 1 1]
 [39.0 123 2 1 1 1]
 [58.0 110 2 1 1 1]
 [62.0 100 2 1 1 1]
 [48.0 90 2 0 1 0]
 [62.0 49 1 1 1 1]
 [65.0 96 2 1 1 1]
 [18.0 67 2 1 1 0]
 [62.0 68 2 1 1 1]
 [61.0 62 1 1 0 1]
 [62.0 55 1 1 1 1]
 [62.0 110 2 1 1 1]
 [62.0 129 2 1 1 1]
 [62.0 109 2 1 1 1]
 [46.0 58 1 1 1 1]
 [46.0 55 1 1 1 1]
 [53.0 150 2 0 1 1]
 [51.0 60 2 1 1 1]
 [19.0 130 3 1 1 0]
 [19.0 88 2 1 1 1]
 [52.0 51 1 1 1 1]
 [44.0 113 3 1 1 0]
 [0.0 110 2 1 1 1]
 [37.0 60 1 1 1 1]
 [33.0 98 2 1 1 1]
 [16.0 62 2 0 0 1]

In [78]:
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size=0.1, random_state=0)

In [79]:
regressor = XGBRegressor()
regressor.fit(xTrain, yTrain)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [80]:
yPred = regressor.predict(xTest)
np.set_printoptions(precision=2)
print(np.concatenate((yPred.reshape(len(yPred),1), yTest.reshape(len(yTest),1)),1))

[[3.33e+09 2.80e+09]
 [2.13e+09 2.20e+09]
 [3.05e+09 2.35e+09]
 [1.04e+09 7.80e+08]
 [1.87e+09 2.15e+09]
 [2.60e+09 2.30e+09]
 [3.69e+09 3.40e+09]
 [1.15e+09 6.20e+08]
 [1.02e+10 1.02e+10]
 [1.32e+09 1.65e+09]
 [2.49e+09 2.80e+09]
 [1.79e+09 1.45e+09]
 [5.60e+08 5.60e+08]
 [2.40e+09 2.03e+09]
 [2.08e+09 2.20e+09]]


In [81]:
r2_score(yTest, yPred)

0.9744696593260145